# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Linux Wireless network device drivers for Realtek units
#

obj-$(CONFIG_RTL8180)		+= rtl818x/
obj-$(CONFIG_RTL8187)		+= rtl818x/
obj-$(CONFIG_RTLWIFI)		+= rtlwifi/
obj-$(CONFIG_RTL8XXXU)		+= rtl8xxxu/
obj-$(CONFIG_RTW88)		+= rtw88/
obj-$(CONFIG_RTL8188EU)		+= rtl8188eu/
obj-$(CONFIG_RTL8188FU)		+= rtl8188fu/
obj-$(CONFIG_RTL8192CU) 	+= rtl8192cu/
obj-$(CONFIG_RTL8192DU) 	+= rtl8192du/
obj-$(CONFIG_RTL8723AU) 	+= rtl8723au/
obj-$(CONFIG_RTL8723BU) 	+= rtl8723bu/
obj-$(CONFIG_RTL8812AU)		+= rtl8812au/
obj-$(CONFIG_RTL8821CU)		+= rtl8821cu/

