# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BCMDHD)		+= bcmdhd/
obj-$(CONFIG_CYW_BCMDHD)	+= cywdhd/
obj-$(CONFIG_ESP8089)		+= esp8089/
obj-$(CONFIG_MVL88W8977)	+= mvl88w8977/
obj-$(CONFIG_RTL8189ES) 	+= rtl8189es/
obj-$(CONFIG_RTL8189FS) 	+= rtl8189fs/
obj-$(CONFIG_RTL8723BS) 	+= rtl8723bs/
obj-$(CONFIG_RTL8723CS)		+= rtl8723cs/
obj-$(CONFIG_RTL8723DS) 	+= rtl8723ds/
obj-$(CONFIG_RTL8822BE)		+= rtl8822be/
obj-$(CONFIG_RTL8822BS) 	+= rtl8822bs/
obj-$(CONFIG_SSV6051)		+= ssv6xxx/
obj-$(CONFIG_WL_ROCKCHIP)	+= wifi_sys/rkwifi_sys_iface.o wifi_sys/rkwifi_config.o


